add google search scrape
CryptoFraudDetection/main pull request #24
Opened 2024-10-09 20:35 UTC by gabrieltorresgamez

Scrape added. Please don't close this request, i want to add the elasticsearch api.

You can use this as a guide to create your scrapers.

2024-10-09 22:15 UTC, gabrieltorresgamez commented
ElasticAPI retrieval and insetion implemented.

Two questions

- [ ] Is the current env variable handling a good solution? Maybe i should add this to the make commands?
- [ ] Sometimes when scraping google, it gets stuck on the second page for 60s. Not huge problem but not perfect nonetheless...

2024-10-10 08:51 UTC, gabrieltorresgamez commented
Feedback Fernando
- Bewertungsraster genauer analysieren
- Überall, wo eine Exception auftauchen kann -> abfangen
- Mehr Kommentare für die bessere Navigation durch den Code
- Brauchen wir beautifulsoup? besser 1 library weniger
- CSS Klassen können sich ändern -> nicht hardcodieren

2024-10-16 12:59 UTC, gabrieltorresgamez commented
Fernando Feedback implemented.

Should I add logging and unit tests?

2024-10-16 19:59 UTC, gabrieltorresgamez commented
how tf did the test pass with selenium????? anyway, logging, tests and typing added pls review

2024-10-17 07:59 UTC, can020202 commented on src/CryptoFraudDetection/scraper/google_results.py
Add more functions in scraper class

2024-10-17 08:13 UTC, can020202 requested changes
Added comments for changes

2024-10-17 08:26 UTC, gabrieltorresgamez commented on src/CryptoFraudDetection/elasticsearch/__init__.py
indeed

2024-10-17 09:18 UTC, gabrieltorresgamez commented
implemented feedback

2024-10-17 17:50 UTC, can020202 approved these changes
Looks good

2024-10-17 18:31 UTC, merged