add comparitech scraper
CryptoFraudDetection/main pull request #31
Opened 2024-10-22 13:14 UTC by gabrieltorresgamez

2024-10-22 13:14 UTC, gabrieltorresgamez commented
oh i forgot tests, dont approve yet

2024-10-22 13:34 UTC, gabrieltorresgamez commented
ok now

2024-10-22 15:48 UTC, can020202 commented on tests/test_scraper_comparitech.py
there is still GoogleResultsScraper in Docstrings

2024-10-22 15:50 UTC, can020202 requested changes
in test_scraper_comparitech.py there is still GoogleResultsScraper in Docstrings, rest looks good

2024-10-22 19:18 UTC, gabrieltorresgamez commented
massive spot, is fixed now :)

2024-10-23 08:27 UTC, can020202 approved these changes
looks good

2024-10-23 09:33 UTC, merged